/**
 * Generate public/sitemap.xml from the actual routes.
 *
 * Runs as part of `npm run build` (prebuild), so the sitemap can never fall
 * behind the site. The previous hand-written version already had a gap: the
 * first PotCast episode was live but unlisted, which is exactly how a page sits
 * undiscovered for weeks. Every new episode added to src/lib/potcast.ts now
 * appears here automatically.
 */
import { readFile, writeFile } from 'node:fs/promises';

const ORIGIN = 'https://www.theroach.co.za';
const OUT = 'public/sitemap.xml';

// Read the episode slugs straight from the source of truth rather than keeping
// a second list in sync. Regex rather than an import because this is a .ts file
// and the build has no TS runtime available at this point.
const src = await readFile('src/lib/potcast.ts', 'utf8');
const slugs = [...src.matchAll(/slug:\s*['"]([^'"]+)['"]/g)].map((m) => m[1]);

const pages = [
  { loc: '/', changefreq: 'monthly', priority: '1.0' },
  { loc: '/potcast/', changefreq: 'weekly', priority: '0.9' },
  ...slugs.map((s) => ({ loc: `/potcast/${s}/`, changefreq: 'monthly', priority: '0.7' })),
];

const xml =
  `<?xml version="1.0" encoding="UTF-8"?>\n` +
  `<!-- Generated by scripts/gen-sitemap.mjs - do not edit by hand. -->\n` +
  `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
  pages
    .map(
      (p) =>
        `  <url>\n` +
        `    <loc>${ORIGIN}${p.loc}</loc>\n` +
        `    <changefreq>${p.changefreq}</changefreq>\n` +
        `    <priority>${p.priority}</priority>\n` +
        `  </url>\n`,
    )
    .join('') +
  `</urlset>\n`;

await writeFile(OUT, xml, 'utf8');
console.log(`sitemap: ${pages.length} URLs (${slugs.length} episode${slugs.length === 1 ? '' : 's'})`);
