/**
 * Generate public/sitemap.xml from the actual routes.
 *
 * Runs as part of `npm run build` (prebuild), so the sitemap can never fall
 * behind the site. The previous hand-written version already had a gap: the
 * first PotCast episode was live but unlisted, which is exactly how a page sits
 * undiscovered for weeks. Every new episode added to src/lib/potcast.ts now
 * appears here automatically.
 */
import { readFile, writeFile } from 'node:fs/promises';

const ORIGIN = 'https://www.theroach.co.za';
const OUT = 'public/sitemap.xml';

// Read the episode slugs straight from the source of truth rather than keeping
// a second list in sync. Regex rather than an import because this is a .ts file
// and the build has no TS runtime available at this point.
const src = await readFile('src/lib/potcast.ts', 'utf8');
const slugs = [...src.matchAll(/slug:\s*['"]([^'"]+)['"]/g)].map((m) => m[1]);

// Blog posts are one markdown file each in content/blog/ — the filename IS the
// slug, so the directory listing is the source of truth. Drafts are excluded
// the same way the build excludes them: `published: false` in frontmatter.
const { readdir } = await import('node:fs/promises');
const postSlugs = [];
try {
  for (const f of await readdir('content/blog')) {
    if (!f.endsWith('.md')) continue;
    const body = await readFile(`content/blog/${f}`, 'utf8');
    if (/^published:\s*false/m.test(body)) continue;
    postSlugs.push(f.replace(/\.md$/, ''));
  }
} catch {
  /* no blog directory yet — fine */
}

const pages = [
  { loc: '/', changefreq: 'monthly', priority: '1.0' },
  { loc: '/potcast/', changefreq: 'weekly', priority: '0.9' },
  ...slugs.map((s) => ({ loc: `/potcast/${s}/`, changefreq: 'monthly', priority: '0.7' })),
  { loc: '/blog/', changefreq: 'weekly', priority: '0.9' },
  ...postSlugs.map((s) => ({ loc: `/blog/${s}/`, changefreq: 'monthly', priority: '0.7' })),
];

const xml =
  `<?xml version="1.0" encoding="UTF-8"?>\n` +
  `<!-- Generated by scripts/gen-sitemap.mjs - do not edit by hand. -->\n` +
  `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
  pages
    .map(
      (p) =>
        `  <url>\n` +
        `    <loc>${ORIGIN}${p.loc}</loc>\n` +
        `    <changefreq>${p.changefreq}</changefreq>\n` +
        `    <priority>${p.priority}</priority>\n` +
        `  </url>\n`,
    )
    .join('') +
  `</urlset>\n`;

await writeFile(OUT, xml, 'utf8');
console.log(`sitemap: ${pages.length} URLs (${slugs.length} episode${slugs.length === 1 ? '' : 's'})`);
